{{- if .development.emacs }}
.config/emacs:
  type: git-repo
  url: https://github.com/ndwarshuis/.emacs.d.git
{{- end }}
{{- if .desktop }}
.config/rofi-extras:
  type: git-repo
  url: https://github.com/ndwarshuis/rofi-extras.git
.config/xmonad:
  type: git-repo
  url: https://github.com/ndwarshuis/xmonad-config.git
.config/xman:
  type: git-repo
  url: https://github.com/ndwarshuis/xman.git
{{- end }}
{{- if ne .features.conky_alias "none" }}
.config/conky:
  type: git-repo
  url: https://github.com/ndwarshuis/universal-conky.git
{{- end }}
.local/share/zsh/plugins/zsh-syntax-highlighting:
  type: git-repo
  url: https://github.com/zsh-users/zsh-syntax-highlighting.git
  clone.args: --branch 0.7.1
