#! /bin/bash

## with_gpg_mount: call a program after mounting GNUPGHOME

bin="$1"
shift

alias="gnupg"

rofi-dev -c "$XDG_CONFIG_HOME/rofi/devices.yml" -m "$alias" \
    && "$bin" "$@" || echo "Could not mount $alias"
