#! /bin/bash

## with_gpg_mount: call a program after mounting GNUPGHOME

bin="$1"
shift

alias="gnupg"

if rofi-dev -c "$XDG_CONFIG_HOME/rofi/devices.dhall" -m "$alias"; then
    "$bin" "$@"
else
    echo "Could not mount $alias"
fi
