#! /bin/bash

# call the brave browser with some nice flags

/usr/bin/brave --process-per-site \
      --disk-cache-dir="/tmp/brave-cache" \
      --use-gl=desktop \
      --enable-accelerated-video-decode \
      --enable-gpu-compositing \
      --enable-gpu-rasterization \
      --enable-oop-rasterization \
      --enable-zero-copy \
      --enable-raw-draw \
      --enable-features=VaapiVideoDecoder,VaapiVideoDecoder,CanvasOopRasterization,WebUIDarkMode \
      --force-dark-mode \
      --use-vulkan \
      "$@"

