#! /bin/bash

# locally install mamba for this user

bin_path=~/.local/bin/mamba_installer.sh
mamba_root=$XDG_DATA_HOME/mambaforge

# this needs to be present or else the installer will fail
mkdir -p $XDG_DATA_HOME/conda/{pkgs,envs}

# TODO configure version
#curl -L -O "https://github.com/conda-forge/miniforge/releases/download/4.13.0-1/Mambaforge-$(uname)-$(uname -m).sh"
curl -L -o "$bin_path" "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"

bash "$bin_path" -p "$mamba_root" -b -f

rm -f "$bin_path"
